services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Mapeia para usar o seu usuário atual do servidor (ex: 1000:1000)
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
